# Generated by Django 5.1.2 on 2026-03-04 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthKnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "manual"),
                            ("file", "file"),
                            ("url", "url"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "source_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("content", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("deleted", "deleted")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "health_rag_knowledge_document",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthKnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField(default=0)),
                ("chunk_text", models.TextField()),
                ("token_count", models.IntegerField(default=0)),
                ("vector_id", models.IntegerField(blank=True, null=True)),
                ("embedding", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="health_rag_assistant.healthknowledgedocument",
                    ),
                ),
            ],
            options={
                "db_table": "health_rag_knowledge_chunk",
                "ordering": ["document_id", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="HealthQASession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="新会话", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "health_rag_qa_session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthQARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True, default="")),
                (
                    "ask_mode",
                    models.CharField(
                        choices=[("text", "text"), ("voice", "voice")],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("source_refs", models.JSONField(blank=True, default=list)),
                ("latency_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="health_rag_assistant.healthqasession",
                    ),
                ),
            ],
            options={
                "db_table": "health_rag_qa_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="healthknowledgedocument",
            index=models.Index(
                fields=["user", "status"], name="health_rag__user_id_a01d66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthknowledgedocument",
            index=models.Index(
                fields=["source_type"], name="health_rag__source__e78072_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthknowledgechunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="health_rag__documen_2073c9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="healthknowledgechunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="healthqasession",
            index=models.Index(
                fields=["user", "updated_at"], name="health_rag__user_id_6f47ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthqarecord",
            index=models.Index(
                fields=["user", "created_at"], name="health_rag__user_id_9a6237_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthqarecord",
            index=models.Index(
                fields=["session", "created_at"], name="health_rag__session_cd424f_idx"
            ),
        ),
    ]
