# Generated by Django 5.1.2 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_rag_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthqarecord",
            name="knowledge_card",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
