# Generated by Django 5.2.6 on 2025-09-23 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HertzRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('role_code', models.CharField(max_length=50, unique=True, verbose_name='角色代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='角色描述')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'hertz_role',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HertzDepartment',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False, verbose_name='部门ID')),
                ('dept_name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('dept_code', models.CharField(max_length=50, unique=True, verbose_name='部门代码')),
                ('leader', models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hertz_studio_django_auth.hertzdepartment', verbose_name='父部门ID')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'hertz_department',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HertzUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('real_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hertz_studio_django_auth.hertzdepartment', verbose_name='部门ID')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'hertz_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HertzMenu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('menu_code', models.CharField(max_length=100, unique=True, verbose_name='菜单代码')),
                ('menu_type', models.IntegerField(choices=[(1, '目录'), (2, '菜单'), (3, '按钮')], verbose_name='菜单类型')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单图标')),
                ('permission', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_external', models.BooleanField(default=False, verbose_name='是否外链')),
                ('is_cache', models.BooleanField(default=True, verbose_name='是否缓存')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hertz_studio_django_auth.hertzmenu', verbose_name='父菜单ID')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'hertz_menu',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HertzRoleMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hertz_studio_django_auth.hertzmenu', verbose_name='菜单')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hertz_studio_django_auth.hertzrole', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色菜单',
                'verbose_name_plural': '角色菜单',
                'db_table': 'hertz_role_menu',
                'unique_together': {('role', 'menu')},
            },
        ),
        migrations.CreateModel(
            name='HertzUserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hertz_studio_django_auth.hertzrole', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'db_table': 'hertz_user_role',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
