# Generated by Django 5.2.6 on 2025-10-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hertz_studio_django_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hertzuser",
            name="last_login_ip",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="最后登录IP"
            ),
        ),
    ]
