# Generated by Django 5.1.2 on 2025-11-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hertz_studio_django_auth", "0002_alter_hertzuser_last_login_ip"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="hertzdepartment",
            table="hertz_auth_department",
        ),
        migrations.AlterModelTable(
            name="hertzmenu",
            table="hertz_auth_menu",
        ),
        migrations.AlterModelTable(
            name="hertzrole",
            table="hertz_auth_role",
        ),
        migrations.AlterModelTable(
            name="hertzrolemenu",
            table="hertz_auth_role_menu",
        ),
        migrations.AlterModelTable(
            name="hertzuser",
            table="hertz_auth_user",
        ),
        migrations.AlterModelTable(
            name="hertzuserrole",
            table="hertz_auth_user_role",
        ),
    ]
