# Generated by Django 5.2.6 on 2025-10-10 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "log_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="日志ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("view", "查看"),
                            ("list", "列表查看"),
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("module", models.CharField(max_length=50, verbose_name="操作模块")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="操作描述"),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="目标模型"
                    ),
                ),
                (
                    "target_id",
                    models.IntegerField(blank=True, null=True, verbose_name="目标ID"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="用户代理"
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(blank=True, null=True, verbose_name="请求数据"),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="响应状态码"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "失败"), (1, "成功")],
                        default=1,
                        verbose_name="操作状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "operation_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="operation_l_user_id_c9af97_idx",
                    ),
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="operation_l_action__88d00b_idx",
                    ),
                    models.Index(
                        fields=["module", "created_at"],
                        name="operation_l_module_72e285_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="operation_l_ip_addr_b4b682_idx",
                    ),
                ],
            },
        ),
    ]
