# Generated by Django 5.1.2 on 2025-11-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hertz_studio_django_log", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="operationlog",
            new_name="hertz_log_o_user_id_d7990f_idx",
            old_name="operation_l_user_id_c9af97_idx",
        ),
        migrations.RenameIndex(
            model_name="operationlog",
            new_name="hertz_log_o_action__2fda9a_idx",
            old_name="operation_l_action__88d00b_idx",
        ),
        migrations.RenameIndex(
            model_name="operationlog",
            new_name="hertz_log_o_module_50c9f0_idx",
            old_name="operation_l_module_72e285_idx",
        ),
        migrations.RenameIndex(
            model_name="operationlog",
            new_name="hertz_log_o_ip_addr_b1b024_idx",
            old_name="operation_l_ip_addr_b4b682_idx",
        ),
        migrations.AlterModelTable(
            name="operationlog",
            table="hertz_log_operation_log",
        ),
    ]
