# Generated by Django 5.1.2 on 2025-10-09 03:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HertzNotice",
            fields=[
                (
                    "notice_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="通知ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "notice_type",
                    models.IntegerField(
                        choices=[
                            (1, "系统通知"),
                            (2, "公告通知"),
                            (3, "活动通知"),
                            (4, "维护通知"),
                        ],
                        default=1,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "低"), (2, "中"), (3, "高"), (4, "紧急")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "草稿"), (1, "已发布"), (2, "已撤回")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                ("is_top", models.BooleanField(default=False, verbose_name="是否置顶")),
                (
                    "publish_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="发布时间"
                    ),
                ),
                (
                    "expire_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(blank=True, null=True, verbose_name="附件链接"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="查看次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "hertz_notice",
                "ordering": ["-is_top", "-priority", "-publish_time"],
            },
        ),
        migrations.CreateModel(
            name="HertzUserNotice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "read_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "is_starred",
                    models.BooleanField(default=False, verbose_name="是否收藏"),
                ),
                (
                    "starred_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="收藏时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notices",
                        to="hertz_studio_django_notice.hertznotice",
                        verbose_name="通知",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户通知状态",
                "verbose_name_plural": "用户通知状态",
                "db_table": "hertz_user_notice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="hertznotice",
            index=models.Index(
                fields=["status", "publish_time"], name="hertz_notic_status_9e9161_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hertznotice",
            index=models.Index(
                fields=["notice_type", "status"], name="hertz_notic_notice__8197ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hertznotice",
            index=models.Index(
                fields=["is_top", "priority"], name="hertz_notic_is_top_ff15ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hertzusernotice",
            index=models.Index(
                fields=["user", "is_read"], name="hertz_user__user_id_e505aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hertzusernotice",
            index=models.Index(
                fields=["user", "is_starred"], name="hertz_user__user_id_0c3c51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hertzusernotice",
            index=models.Index(
                fields=["notice", "is_read"], name="hertz_user__notice__3a40de_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hertzusernotice",
            unique_together={("user", "notice")},
        ),
    ]
