# Generated by Django 5.1.2 on 2025-10-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hertz_studio_django_notice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hertznotice",
            name="status",
            field=models.IntegerField(
                choices=[(0, "草稿"), (1, "已发布"), (2, "已撤回")],
                default=0,
                verbose_name="状态",
            ),
        ),
    ]
