# Generated by Django 5.1.2 on 2025-11-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hertz_studio_django_notice", "0002_alter_hertznotice_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="hertznotice",
            new_name="hertz_studi_status_8868be_idx",
            old_name="hertz_notic_status_9e9161_idx",
        ),
        migrations.RenameIndex(
            model_name="hertznotice",
            new_name="hertz_studi_notice__7bda0f_idx",
            old_name="hertz_notic_notice__8197ac_idx",
        ),
        migrations.RenameIndex(
            model_name="hertznotice",
            new_name="hertz_studi_is_top_50e030_idx",
            old_name="hertz_notic_is_top_ff15ec_idx",
        ),
        migrations.RenameIndex(
            model_name="hertzusernotice",
            new_name="hertz_studi_user_id_92c07a_idx",
            old_name="hertz_user__user_id_e505aa_idx",
        ),
        migrations.RenameIndex(
            model_name="hertzusernotice",
            new_name="hertz_studi_user_id_94b9f7_idx",
            old_name="hertz_user__user_id_0c3c51_idx",
        ),
        migrations.RenameIndex(
            model_name="hertzusernotice",
            new_name="hertz_studi_notice__4a28b7_idx",
            old_name="hertz_user__notice__3a40de_idx",
        ),
        migrations.AlterModelTable(
            name="hertznotice",
            table="hertz_studio_django_notice_HertzNotice",
        ),
        migrations.AlterModelTable(
            name="hertzusernotice",
            table="hertz_studio_django_notice_HertzUserNotice",
        ),
    ]
