# Generated by Django 5.1.2 on 2025-11-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "hertz_studio_django_notice",
            "0003_hertznotice_indexes_and_table",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="hertznotice",
            new_name="hertz_notic_status_dcefc5_idx",
            old_name="hertz_studi_status_8868be_idx",
        ),
        migrations.RenameIndex(
            model_name="hertznotice",
            new_name="hertz_notic_notice__36060b_idx",
            old_name="hertz_studi_notice__7bda0f_idx",
        ),
        migrations.RenameIndex(
            model_name="hertznotice",
            new_name="hertz_notic_is_top_b14408_idx",
            old_name="hertz_studi_is_top_50e030_idx",
        ),
        migrations.RenameIndex(
            model_name="hertzusernotice",
            new_name="hertz_notic_user_id_b0f970_idx",
            old_name="hertz_studi_user_id_92c07a_idx",
        ),
        migrations.RenameIndex(
            model_name="hertzusernotice",
            new_name="hertz_notic_user_id_aba0ac_idx",
            old_name="hertz_studi_user_id_94b9f7_idx",
        ),
        migrations.RenameIndex(
            model_name="hertzusernotice",
            new_name="hertz_notic_notice__f96884_idx",
            old_name="hertz_studi_notice__4a28b7_idx",
        ),
        migrations.AlterModelTable(
            name="hertznotice",
            table="hertz_notice_notice",
        ),
        migrations.AlterModelTable(
            name="hertzusernotice",
            table="hertz_notice_user_notice",
        ),
    ]
